//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyekPAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class barang
    {
        public string id_barang { get; set; }
        public string nama_barang { get; set; }
        public Nullable<int> harga_beli { get; set; }
        public Nullable<int> harga_jual { get; set; }
        public Nullable<int> stok_barang { get; set; }
        public string id_diskon { get; set; }
        public string id_voucher { get; set; }
    
        public virtual diskon diskon { get; set; }
        public virtual voucher voucher { get; set; }
    }
}
